kind: Service
apiVersion: v1
metadata:
  name: harkap-ambulance-webapi
spec:
  selector:
    pod: harkap-ambulance-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
