/*
 * Device List Api
 *
 * Ambulance Device List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package ambulance_wl

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type AmbulanceDeviceListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateDeviceListEntry - Saves new entry into device list
   CreateDeviceListEntry(ctx *gin.Context)

    // DeleteDeviceListEntry - Deletes specific entry
   DeleteDeviceListEntry(ctx *gin.Context)

    // GetDeviceListEntries - Provides the ambulance device list
   GetDeviceListEntries(ctx *gin.Context)

    // GetDeviceListEntry - Provides details about device list entry
   GetDeviceListEntry(ctx *gin.Context)

    // UpdateDeviceListEntry - Updates specific entry
   UpdateDeviceListEntry(ctx *gin.Context)

}

// partial implementation of AmbulanceDeviceListAPI - all functions must be implemented in add on files
type implAmbulanceDeviceListAPI struct {

}

func newAmbulanceDeviceListAPI() AmbulanceDeviceListAPI {
  return &implAmbulanceDeviceListAPI{}
}

func (this *implAmbulanceDeviceListAPI) addRoutes(routerGroup *gin.RouterGroup) {
  routerGroup.Handle( http.MethodPost, "/device-list/entries", this.CreateDeviceListEntry)
  routerGroup.Handle( http.MethodDelete, "/device-list/entries/:entryId", this.DeleteDeviceListEntry)
  routerGroup.Handle( http.MethodGet, "/device-list/entries", this.GetDeviceListEntries)
  routerGroup.Handle( http.MethodGet, "/device-list/entries/:entryId", this.GetDeviceListEntry)
  routerGroup.Handle( http.MethodPut, "/device-list/entries/:entryId", this.UpdateDeviceListEntry)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateDeviceListEntry - Saves new entry into device list
// func (this *implAmbulanceDeviceListAPI) CreateDeviceListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteDeviceListEntry - Deletes specific entry
// func (this *implAmbulanceDeviceListAPI) DeleteDeviceListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetDeviceListEntries - Provides the ambulance device list
// func (this *implAmbulanceDeviceListAPI) GetDeviceListEntries(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetDeviceListEntry - Provides details about device list entry
// func (this *implAmbulanceDeviceListAPI) GetDeviceListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateDeviceListEntry - Updates specific entry
// func (this *implAmbulanceDeviceListAPI) UpdateDeviceListEntry(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

