/*
 * Device List Api
 *
 * Ambulance Device List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

// Department - Department of the hospital
type Department struct {

	Name string `json:"name"`

	Code string `json:"code,omitempty"`
}
