/*
 * Device List Api
 *
 * Ambulance Device List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: <your_email>
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"time"
)

type DeviceLog struct {

	// Unique id of the log
	Id string `json:"id"`

	// Text of log operation
	Text string `json:"text"`

	// Unique identifier of the device
	DeviceId string `json:"deviceId"`

	// Timestamp since when the patient entered the waiting list
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
